name: Scrape Schedule

on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Run scraper
        run: npm run scrape

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain data/schedule.json)" ]; then
            git add data/schedule.json
            git commit -m "chore: update schedule.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
